### PR TITLE
fix: "Solve the problem that the resources have not been fully released due to early exit"

### PR DESCRIPTION
**Pull request by JeffreyBool**

### CODE REVIEW

**Comment by JeffreyBool** [comment]
@asim

**Comment by asim** [comment]
There's a bunch of random go mod changes and the build is broken

**Comment by JeffreyBool** [comment]
> There's a bunch of random go mod changes and the build is broken

It's not mod, it's because I exposed the run error

**Comment by JeffreyBool** [comment]
@asim  It's solved

**Pull request merged**
